import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

export function slugify(id: string | string, str: string) {
    str = str.replace(/^\s+|\s+$/g, '')
    str = str.toLowerCase()
    str = str.replace(/[^a-z0-9 -]/g, '')
    str = str.replace(/\s+/g, '-')
    str = str.replace(/-+/g, '-')
    return `${id}-${str}`
}

async function main() {
    const createBuild = async (build: any) => {
        const { id: buildId, name } = await prisma.builds.create({
            data: build,
        })

        await prisma.builds.update({
            where: {
                id: buildId,
            },
            data: {
                slug: slugify(buildId, name),
            },
        })
        return buildId
    }

    const userId = (
        await prisma.user.create({
            data: {
                id: 'test-39a9-test-863b-test',
                name: 'test',
                preferred_username: 'test',
                given_name: 'test',
                family_name: 'test',
                email: 'test@gmail.com',
            },
        })
    ).id

    const buildId = await createBuild({
        name: 'Zerg Rush',
        description: 'Une stratégie ultra-agressive basée sur les Zerglings.',
        slug: 'zerg-rush',
        race: 'ZERG',
        v_race: 'TERRAN',
        is_public: true,
        userId,
        picture_url: 'https://example.com/zerg-rush.jpg',
        difficulty: 2,
        type: 'agressive',
    })

    await prisma.step.createMany({
        data: [
            {
                description: 'Envoyer les ouvriers récolter les minéraux',
                population: 12,
                timer: 0,
                position: 1,
                buildId,
            },
            {
                description: 'Construire un Extracteur et assigner 3 ouvriers',
                population: 13,
                timer: 20,
                position: 2,
                buildId,
            },
            {
                description: 'Construire une Piscine Génétique',
                population: 14,
                timer: 40,
                position: 3,
                buildId,
            },
            {
                description: 'Former 6 Zerglings dès que possible',
                population: 14,
                timer: 80,
                position: 4,
                buildId,
            },
            {
                description: "Envoyer les Zerglings attaquer l'ennemi",
                population: 14,
                timer: 120,
                position: 5,
                buildId,
            },
            {
                description: 'Continuer à produire des Zerglings',
                population: 16,
                timer: 140,
                position: 6,
                buildId,
            },
            {
                description: 'Construire une Reine pour injecter du mucus',
                population: 18,
                timer: 160,
                position: 7,
                buildId,
            },
            {
                description: 'Construire un deuxième Extracteur',
                population: 19,
                timer: 180,
                position: 8,
                buildId,
            },
            {
                description:
                    "Lancer l'amélioration de la vitesse des Zerglings",
                population: 20,
                timer: 200,
                position: 9,
                buildId,
            },
            {
                description: 'Construire une deuxième base',
                population: 21,
                timer: 220,
                position: 10,
                buildId,
            },
            {
                description: 'Produire encore plus de Zerglings',
                population: 22,
                timer: 240,
                position: 11,
                buildId,
            },
            {
                description: 'Scout avec un Zergling pour voir la base ennemie',
                population: 22,
                timer: 260,
                position: 12,
                buildId,
            },
            {
                description: "Lancer l'amélioration des attaques des Zerglings",
                population: 24,
                timer: 280,
                position: 13,
                buildId,
            },
            {
                description: "Construire une Chambre d'évolution",
                population: 24,
                timer: 300,
                position: 14,
                buildId,
            },
            {
                description: 'Créer une deuxième Reine pour la défense',
                population: 26,
                timer: 320,
                position: 15,
                buildId,
            },
            {
                description:
                    "Envoyer des Zerglings harceler l'économie ennemie",
                population: 26,
                timer: 340,
                position: 16,
                buildId,
            },
            {
                description:
                    'Construire une Reine supplémentaire pour la macro',
                population: 28,
                timer: 360,
                position: 17,
                buildId,
            },
            {
                description:
                    'Faire évoluer la Tanière pour débloquer les Cafards',
                population: 30,
                timer: 380,
                position: 18,
                buildId,
            },
            {
                description: 'Lancer la production de Cafards',
                population: 32,
                timer: 400,
                position: 19,
                buildId,
            },
            {
                description: 'Construire un troisième Extracteur',
                population: 34,
                timer: 420,
                position: 20,
                buildId,
            },
            {
                description:
                    'Envoyer des Zerglings explorer les points stratégiques',
                population: 36,
                timer: 440,
                position: 21,
                buildId,
            },
            {
                description: 'Améliorer les armures des unités terrestres',
                population: 38,
                timer: 460,
                position: 22,
                buildId,
            },
            {
                description: 'Construire un Terrier pour cacher les unités',
                population: 40,
                timer: 480,
                position: 23,
                buildId,
            },
            {
                description: 'Construire un Spire pour accéder aux Mutalisks',
                population: 42,
                timer: 500,
                position: 24,
                buildId,
            },
            {
                description: 'Former les premiers Mutalisks',
                population: 44,
                timer: 520,
                position: 25,
                buildId,
            },
            {
                description:
                    'Préparer une attaque combinée Zerglings + Mutalisks',
                population: 46,
                timer: 540,
                position: 26,
                buildId,
            },
            {
                description: 'Lancer une attaque massive',
                population: 48,
                timer: 560,
                position: 27,
                buildId,
            },
            {
                description:
                    'Produire des Overlords pour éviter le supply block',
                population: 50,
                timer: 580,
                position: 28,
                buildId,
            },
            {
                description: 'Construire une troisième base',
                population: 52,
                timer: 600,
                position: 29,
                buildId,
            },
            {
                description: 'Continuer la production de Mutalisks',
                population: 54,
                timer: 620,
                position: 30,
                buildId,
            },
            {
                description: 'Faire évoluer les Cafards en Cafards fouisseurs',
                population: 56,
                timer: 640,
                position: 31,
                buildId,
            },
            {
                description:
                    'Harceler les lignes de minerais ennemies avec les Mutalisks',
                population: 58,
                timer: 660,
                position: 32,
                buildId,
            },
            {
                description: 'Préparer une attaque finale',
                population: 60,
                timer: 680,
                position: 33,
                buildId,
            },
            {
                description: 'Maximiser la production de troupes',
                population: 62,
                timer: 700,
                position: 34,
                buildId,
            },
            {
                description: "Achever l'adversaire avec une armée complète",
                population: 64,
                timer: 720,
                position: 35,
                buildId,
            },
        ],
    })

    const builds = [
        {
            name: 'Marine Tank Push',
            description: 'Un push puissant basé sur Marines et Tanks.',
            slug: 'marine-tank-push',
            race: 'TERRAN',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/marine-tank-push.jpg',
            difficulty: 3,
            type: 'timing-push',
        },
        {
            name: 'Cannon Rush',
            description: 'Une stratégie basée sur le proxy de Photons Cannons.',
            slug: 'cannon-rush',
            race: 'PROTOSS',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/cannon-rush.jpg',
            difficulty: 2,
            type: 'cheese',
        },
        {
            name: 'Roach Ravager All-in',
            description: 'Un all-in basé sur les Roachs et Ravagers.',
            slug: 'roach-ravager-all-in',
            race: 'ZERG',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/roach-ravager-all-in.jpg',
            difficulty: 3,
            type: 'agressive',
        },
        {
            name: 'Dark Templar Rush',
            description: 'Une ouverture rapide sur Dark Templars.',
            slug: 'dark-templar-rush',
            race: 'PROTOSS',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/dark-templar-rush.jpg',
            difficulty: 2,
            type: 'cheese',
        },
        {
            name: 'Banshee Harass',
            description: 'Un harass basé sur des Banshees invisibles.',
            slug: 'banshee-harass',
            race: 'TERRAN',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/banshee-harass.jpg',
            difficulty: 3,
            type: 'harass',
        },
        {
            name: 'Swarm Host Nydus',
            description: 'Une stratégie basée sur Swarm Hosts et le Nydus.',
            slug: 'swarm-host-nydus',
            race: 'ZERG',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/swarm-host-nydus.jpg',
            difficulty: 4,
            type: 'macro-agressive',
        },
        {
            name: 'Colossus Deathball',
            description:
                'Une composition de fin de partie avec Colossus et Gateway units.',
            slug: 'colossus-deathball',
            race: 'PROTOSS',
            v_race: 'ALL',
            is_public: true,
            userId,
            picture_url: 'https://example.com/colossus-deathball.jpg',
            difficulty: 5,
            type: 'macro',
        },
        {
            name: 'Battlecruiser Rush',
            description: 'Un rush rapide basé sur les Battlecruisers.',
            slug: 'battlecruiser-rush',
            race: 'TERRAN',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/battlecruiser-rush.jpg',
            difficulty: 4,
            type: 'tech',
        },
        {
            name: 'Ling Bane All-in',
            description: 'Une attaque tout-en-un avec Zerglings et Banelings.',
            slug: 'ling-bane-all-in',
            race: 'ZERG',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/ling-bane-all-in.jpg',
            difficulty: 3,
            type: 'agressive',
        },
        {
            name: 'Proxy Barracks Reaper',
            description: 'Une ouverture aggressive avec des Reapers.',
            slug: 'proxy-barracks-reaper',
            race: 'TERRAN',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/proxy-barracks-reaper.jpg',
            difficulty: 2,
            type: 'cheese',
        },
        {
            name: 'Fast Carriers',
            description:
                'Une montée rapide sur Carrier avec une économie solide.',
            slug: 'fast-carriers',
            race: 'PROTOSS',
            v_race: 'ALL',
            is_public: true,
            userId,
            picture_url: 'https://example.com/fast-carriers.jpg',
            difficulty: 5,
            type: 'macro-tech',
        },
        {
            name: 'Mech Terran',
            description: 'Un style défensif basé sur les unités mécaniques.',
            slug: 'mech-terran',
            race: 'TERRAN',
            v_race: 'ALL',
            is_public: true,
            userId,
            picture_url: 'https://example.com/mech-terran.jpg',
            difficulty: 4,
            type: 'macro',
        },
        {
            name: 'Speedling Flood',
            description: 'Un assaut rapide avec des Zerglings améliorés.',
            slug: 'speedling-flood',
            race: 'ZERG',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/speedling-flood.jpg',
            difficulty: 2,
            type: 'agressive',
        },
        {
            name: 'Blink Stalker All-in',
            description: 'Un all-in basé sur les Stalkers avec Blink.',
            slug: 'blink-stalker-all-in',
            race: 'PROTOSS',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/blink-stalker-all-in.jpg',
            difficulty: 3,
            type: 'timing-push',
        },
        {
            name: 'Hellion Harass',
            description: 'Une stratégie de harcèlement avec des Hellions.',
            slug: 'hellion-harass',
            race: 'TERRAN',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/hellion-harass.jpg',
            difficulty: 2,
            type: 'harass',
        },
        {
            name: 'Roach Max',
            description: 'Un style macro visant un max de Roachs en 7 min.',
            slug: 'roach-max',
            race: 'ZERG',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/roach-max.jpg',
            difficulty: 4,
            type: 'macro-agressive',
        },
        {
            name: 'Oracle Harass',
            description: 'Un harcèlement rapide avec Oracles.',
            slug: 'oracle-harass',
            race: 'PROTOSS',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/oracle-harass.jpg',
            difficulty: 3,
            type: 'harass',
        },
        {
            name: '2 Base Muta',
            description: 'Une montée rapide sur Mutalisks depuis deux bases.',
            slug: '2-base-muta',
            race: 'ZERG',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/2-base-muta.jpg',
            difficulty: 4,
            type: 'macro',
        },
        {
            name: 'Thor Rush',
            description: 'Une stratégie surprenante avec un push Thor rapide.',
            slug: 'thor-rush',
            race: 'TERRAN',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/thor-rush.jpg',
            difficulty: 3,
            type: 'cheese',
        },
        {
            name: 'Warp Prism All-in',
            description: 'Un all-in utilisant un Warp Prism et des Zealots.',
            slug: 'warp-prism-all-in',
            race: 'PROTOSS',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/warp-prism-all-in.jpg',
            difficulty: 3,
            type: 'timing-push',
        },
        {
            name: '3 Rax Stim Push',
            description: 'Une forte attaque avec Stimpack et Marines.',
            slug: '3-rax-stim-push',
            race: 'TERRAN',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/3-rax-stim-push.jpg',
            difficulty: 3,
            type: 'timing-push',
        },
        {
            name: 'Nydus All-in',
            description: 'Un all-in rapide utilisant le Nydus Worm.',
            slug: 'nydus-all-in',
            race: 'ZERG',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/nydus-all-in.jpg',
            difficulty: 3,
            type: 'cheese',
        },
        {
            name: 'Disruptor Drop',
            description:
                'Un drop rapide de Disruptors pour maximiser les dégâts.',
            slug: 'disruptor-drop',
            race: 'PROTOSS',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/disruptor-drop.jpg',
            difficulty: 4,
            type: 'harass',
        },
        {
            name: 'Ghost Mech Hybrid',
            description: 'Un mix puissant de Ghosts et Mech.',
            slug: 'ghost-mech-hybrid',
            race: 'TERRAN',
            v_race: 'ALL',
            is_public: true,
            userId,
            picture_url: 'https://example.com/ghost-mech-hybrid.jpg',
            difficulty: 5,
            type: 'macro-tech',
        },
        {
            name: 'Ultra Infestor',
            description: 'Une composition tardive ultra puissante.',
            slug: 'ultra-infestor',
            race: 'ZERG',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/ultra-infestor.jpg',
            difficulty: 5,
            type: 'late-game',
        },
        {
            name: 'Phoenix Adept Pressure',
            description: 'Une pression rapide avec Phoenix et Adepts.',
            slug: 'phoenix-adept-pressure',
            race: 'PROTOSS',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/phoenix-adept-pressure.jpg',
            difficulty: 3,
            type: 'timing-push',
        },
        {
            name: 'Planetary Fortress Rush',
            description:
                'Une approche troll avec un CC avancé transformé en PF.',
            slug: 'planetary-fortress-rush',
            race: 'TERRAN',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/planetary-fortress-rush.jpg',
            difficulty: 2,
            type: 'cheese',
        },
        {
            name: '12 Pool All-in',
            description:
                'Un all-in ultra-agressif basé sur un pool à 12 de population.',
            slug: '12-pool-all-in',
            race: 'ZERG',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/12-pool-all-in.jpg',
            difficulty: 2,
            type: 'cheese',
        },
        {
            name: 'Speedling Bane',
            description:
                'Un classique ZvZ basé sur les Zerglings et Banelings.',
            slug: 'speedling-bane',
            race: 'ZERG',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/speedling-bane.jpg',
            difficulty: 3,
            type: 'agressive',
        },
        {
            name: 'Fast Roach Warren',
            description:
                'Une ouverture rapide sur Roachs pour contrer les Banelings.',
            slug: 'fast-roach-warren',
            race: 'ZERG',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/fast-roach-warren.jpg',
            difficulty: 3,
            type: 'timing-push',
        },
        {
            name: 'Muta vs Muta',
            description:
                'Une approche macro avec des Mutalisks et une économie solide.',
            slug: 'muta-vs-muta',
            race: 'ZERG',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/muta-vs-muta.jpg',
            difficulty: 4,
            type: 'macro',
        },
        {
            name: 'Roach Ravager Timing',
            description: 'Un push puissant avec Roachs et Ravagers.',
            slug: 'roach-ravager-timing',
            race: 'ZERG',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/roach-ravager-timing.jpg',
            difficulty: 3,
            type: 'timing-push',
        },
        {
            name: 'Fast Nydus Queen',
            description:
                'Un Nydus rapide avec des Queens pour submerger l’ennemi.',
            slug: 'fast-nydus-queen',
            race: 'ZERG',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/fast-nydus-queen.jpg',
            difficulty: 4,
            type: 'cheese',
        },
        {
            name: 'Hydra Ling Timing',
            description: 'Une transition rapide vers Hydralisks et Zerglings.',
            slug: 'hydra-ling-timing',
            race: 'ZERG',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/hydra-ling-timing.jpg',
            difficulty: 4,
            type: 'timing-push',
        },
        {
            name: 'Ultra Late Game',
            description: 'Une composition ultime avec Ultralisks et Infestors.',
            slug: 'ultra-late-game',
            race: 'ZERG',
            v_race: 'ZERG',
            is_public: true,
            userId,
            picture_url: 'https://example.com/ultra-late-game.jpg',
            difficulty: 5,
            type: 'late-game',
        },
        {
            name: '4 Gate Blink Stalker',
            description:
                'Un all-in classique basé sur des Stalkers avec Blink.',
            slug: '4-gate-blink-stalker',
            race: 'PROTOSS',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/4-gate-blink-stalker.jpg',
            difficulty: 3,
            type: 'timing-push',
        },
        {
            name: 'Proxy 2 Gate Zealot Rush',
            description:
                'Un cheese ultra-agressif avec deux portails en proxy.',
            slug: 'proxy-2-gate-zealot-rush',
            race: 'PROTOSS',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/proxy-2-gate-zealot-rush.jpg',
            difficulty: 2,
            type: 'cheese',
        },
        {
            name: 'Fast Phoenix Play',
            description:
                'Un jeu basé sur une flotte rapide de Phoenix pour dominer les airs.',
            slug: 'fast-phoenix-play',
            race: 'PROTOSS',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/fast-phoenix-play.jpg',
            difficulty: 4,
            type: 'harass',
        },
        {
            name: 'Colossus Double Forge',
            description:
                'Une approche macro avec des améliorations et des Colosses.',
            slug: 'colossus-double-forge',
            race: 'PROTOSS',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/colossus-double-forge.jpg',
            difficulty: 5,
            type: 'macro',
        },
        {
            name: 'DT Rush',
            description:
                'Une ouverture rapide avec des Dark Templars pour surprendre l’adversaire.',
            slug: 'dt-rush',
            race: 'PROTOSS',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/dt-rush.jpg',
            difficulty: 3,
            type: 'cheese',
        },
        {
            name: '1 Gate Fast Expand',
            description:
                'Une ouverture macro pour sécuriser une deuxième base rapidement.',
            slug: '1-gate-fast-expand',
            race: 'PROTOSS',
            v_race: 'PROTOSS',
            is_public: true,
            userId,
            picture_url: 'https://example.com/1-gate-fast-expand.jpg',
            difficulty: 4,
            type: 'macro',
        },
        {
            name: '1/1/1 Standard Opener',
            description:
                'Une ouverture flexible avec une Factory, un Starport et une Barracks.',
            slug: '1-1-1-standard-opener',
            race: 'TERRAN',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/1-1-1-standard-opener.jpg',
            difficulty: 3,
            type: 'standard',
        },
        {
            name: 'Proxy Reaper Rush',
            description:
                'Un cheese avec des Reapers en proxy pour harceler rapidement.',
            slug: 'proxy-reaper-rush',
            race: 'TERRAN',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/proxy-reaper-rush.jpg',
            difficulty: 2,
            type: 'cheese',
        },
        {
            name: 'Cyclone Hellion Pressure',
            description:
                'Un timing push avec Cyclones et Hellions pour surprendre l’adversaire.',
            slug: 'cyclone-hellion-pressure',
            race: 'TERRAN',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/cyclone-hellion-pressure.jpg',
            difficulty: 3,
            type: 'timing-push',
        },
        {
            name: 'Mech Turtle Play',
            description:
                'Une stratégie défensive avec Tanks, Thors et Battlecruisers.',
            slug: 'mech-turtle-play',
            race: 'TERRAN',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/mech-turtle-play.jpg',
            difficulty: 5,
            type: 'macro',
        },
        {
            name: 'BC Rush',
            description:
                'Une montée rapide sur Battlecruisers pour prendre le contrôle du ciel.',
            slug: 'bc-rush',
            race: 'TERRAN',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/bc-rush.jpg',
            difficulty: 4,
            type: 'tech',
        },
        {
            name: 'Marine Tank Push',
            description:
                'Un push classique avec Marines et Tanks, très efficace en TvT.',
            slug: 'marine-tank-push',
            race: 'TERRAN',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/marine-tank-push.jpg',
            difficulty: 3,
            type: 'timing-push',
        },
        {
            name: 'Banshee Cloak Harass',
            description:
                'Une stratégie basée sur le harcèlement avec des Banshees camouflées.',
            slug: 'banshee-cloak-harass',
            race: 'TERRAN',
            v_race: 'TERRAN',
            is_public: true,
            userId,
            picture_url: 'https://example.com/banshee-cloak-harass.jpg',
            difficulty: 4,
            type: 'harass',
        },
    ]

    for (let index = 0; index < builds.length; index++) {
        const element = builds[index]
        await createBuild(element)
    }
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })
